export const container: string;
export const form: string;
export const heading: string;
export const pageInfo: string;
export const pageInfoMessage: string;
export const pageInfoNext: string;
export const pageInfoPage: string;
export const pageInfoPrev: string;
export const wrapper: string;
